steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/primordia:$BUILD_ID", "."]

  # 2. Push it to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/primordia:$BUILD_ID"]

  # 3. Deploy it to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "primordia"
      - "--image=gcr.io/$PROJECT_ID/primordia:$BUILD_ID"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      # THIS IS THE CRITICAL NEW LINE
      - "--service-account=primordia-sa@${_PROJECT_ID}.iam.gserviceaccount.com"
      - "--set-env-vars=PROJECT_ID=${_PROJECT_ID},REGION=${_REGION},WORKSPACE_BUCKET=${_WORKSPACE_BUCKET},CACHE_COLLECTION=${_CACHE_COLLECTION},TASKS_COLLECTION=${_TASKS_COLLECTION}"

images:
  - "gcr.io/$PROJECT_ID/primordia:$BUILD_ID"

substitutions:
  _PROJECT_ID: ""
  _REGION: ""
  _WORKSPACE_BUCKET: ""
  _CACHE_COLLECTION: ""
  _TASKS_COLLECTION: ""
